# Generated by Django 5.1.5 on 2025-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_bn",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_hi",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_bn",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_hi",
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_translations",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Answer Translations"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_translations",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Question Translations"
            ),
        ),
    ]
