# Generated by Django 5.1.5 on 2025-01-31 15:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_remove_faq_answer_bn_remove_faq_answer_hi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_translations",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_translations",
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_bn",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Answer in Bengali"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Answer in Hindi"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_bn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Question in Bengali"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="Question in Hindi"
            ),
        ),
    ]
